# Generated by Django 4.2.13 on 2025-03-03 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('ORG_ADMIN', 'Organisation Admin'), ('ORG_EDITOR', 'Organisation Editor'), ('ORG_VIEWER', 'Organisation Viewer')], default='ORG_ADMIN', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DEPT_ADMIN', 'Department Admin'), ('DEPT_EDITOR', 'Department Editor'), ('DEPT_VIEWER', 'Department Viewer')], max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dept_admins', to='admin_app.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_admins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
