# Generated by Django 4.2.13 on 2025-03-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('admin_type', models.CharField(choices=[('organisation', 'Organisation'), ('department', 'Department')], default='department', max_length=50)),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_for_department', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=15, unique=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('last_logged_in', models.DateTimeField(blank=True, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
