# Generated by Django 4.2.13 on 2025-03-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_for_department', models.BigIntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('university_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.BigIntegerField(unique=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('last_logged_in', models.DateTimeField(blank=True, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_count', models.BigIntegerField(default=0)),
            ],
        ),
    ]
