# Generated by Django 4.2.13 on 2025-03-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='admin_type',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='created_for_department',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='password',
        ),
        migrations.AddField(
            model_name='appuser',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_no',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='reset_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='university_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('registered_user', 'Registered User'), ('guest_user', 'Guest User')], max_length=50, null=True),
        ),
    ]
