# Generated by Django 4.2.13 on 2025-03-03 04:17

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_for', models.CharField(max_length=255)),
                ('total_questions', models.BigIntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('exam_org', models.CharField(max_length=255)),
                ('question_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None)),
                ('exam_type', models.CharField(max_length=255)),
                ('total_marks', models.BigIntegerField()),
                ('duration', models.TimeField()),
                ('time_per_ques', models.TimeField()),
                ('exam_prefix', models.CharField(max_length=255)),
                ('reset_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
